# Generated by Django 4.2 on 2023-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('編號', models.IntegerField(default=0)),
                ('發生日期', models.CharField(max_length=100)),
                ('原因', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('編號',),
            },
        ),
    ]
