# Generated by Django 4.0.6 on 2023-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('accident_year_month', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('township', models.CharField(max_length=100)),
                ('death_toll', models.IntegerField()),
                ('Injured_umber', models.IntegerField()),
                ('weather_description', models.CharField(max_length=100)),
                ('light_description', models.CharField(max_length=100)),
                ('road_description', models.CharField(max_length=100)),
                ('speed_limit', models.IntegerField()),
                ('description_of_road_type', models.CharField(max_length=100)),
                ('description_of_road_conditions', models.CharField(max_length=100)),
                ('description_of_pavement_defects', models.CharField(max_length=100)),
                ('obstacle_description', models.CharField(max_length=100)),
                ('accident_type_and_pattern', models.IntegerField()),
                ('accident_type_and_description', models.CharField(max_length=100)),
                ('surveillance_tape', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('serial_number',),
            },
        ),
        migrations.DeleteModel(
            name='HBicycleData',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='maker',
        ),
        migrations.DeleteModel(
            name='PhoneMaker',
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
