# Generated by Django 4.2 on 2023-06-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardata',
            options={'ordering': ('serial_number',)},
        ),
        migrations.RenameField(
            model_name='cardata',
            old_name='原因',
            new_name='date_of_occurrence',
        ),
        migrations.RenameField(
            model_name='cardata',
            old_name='發生日期',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='cardata',
            old_name='編號',
            new_name='serial_number',
        ),
    ]
