# Generated by Django 4.0.6 on 2023-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_cardata_delete_hbicycledata_remove_phonemodel_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='Injured_umber',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='accident_type_and_pattern',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='death_toll',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='speed_limit',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
