# Generated by Django 4.0.6 on 2023-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_cardata_injured_umber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='accident_year_month',
            field=models.DateField(help_text='事故年月'),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='company_name',
            field=models.CharField(help_text='單位名稱', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='township',
            field=models.CharField(help_text='鄉鎮市區', max_length=100),
        ),
    ]
